apiVersion: apps/v1
kind: Deployment
metadata:
  name: artifact-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: artifact
  template:
    metadata:
      labels:
        app: artifact
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: art-net-prediction
        image: arienarien/art-net:low-train
        ports:
        - containerPort: 5000